### ISSUE TITLE
Build and dev scripts fail on Linux

### ISSUE THREAD

**Issue by droid001** [digaverse/webxr-webpack-boilerplate#20]
**Describe the bug**  
start and build script fails with following message: 
`Error: Cannot find module '../../app'`

**Please complete the following information**  
 - Device: DELL XPS13
 - OS: Ubuntu 18.04
 - Browser (if any):
 - WebXR Webpack Boilerplate Version: 0.9.16

**Comment by mkungla** [comment]
Have you followed initial setup guide https://github.com/digaverse/webxr-webpack-boilerplate#first-run
Error indicates that you don't have `app.json` and probably `app-dev.json` in your project root which you should copy from

```
# copy app-dev.json
cp example.app-dev.json app-dev.json
# copy  app.json
cp example.app.json app.json
```

By default these files are ignored by git.

**Comment by droid001** [comment]
Yep. My bad. I was looking at an other boilerplate readme while dabbling with this and therefore didn't follow the instructions. Sorry about that.
